services:
  mysql:
    image: mysql:8.4
    container_name: ecoride-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride-rental

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/demo.sql:/docker-entrypoint-initdb.d/ecoride-rental.sql

volumes:
  mysql_data: